[package]
name = "sdf_2d"
version = "0.1.0"
authors = ["doup <asier@illarra.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_math = "0.4.0"
minifb = "0.19.2"
rayon = "1.0"
png = "0.16.8"
